### ISSUE TITLE
$golden is used instead of $ratio

### ISSUE THREAD

**Issue by celsomiranda** [corysimmons/typographic#16]
All over the stylesheet you use the $golden variable instead of the ratio. This makes the $ratio setting useless in term of definig the actual scale.

**Comment by corysimmons** [comment]
This is an intentional decision.

I think a `line-height` of around `1.6` is the best line-height, and everything else revolves around that line-height.

Consider if we used the ratio instead, `$minor-second` would have a line-height of `1.067` which would cause characters to almost touch each other.

`margin` is also set with `$golden` to maintain some sense of vertical rhythm.

The `$ratio` setting still has value as it changes the size of the fonts relative to a ratio, so `$double-octave` is about 4 times bigger than `$minor-second` with steps in between.

I agree it would be cool if there were some way to change `line-height` and `margin` according to the `ratio` but the fact is, it just looks horrible for some sizes whereas `golden` makes it all look really good.

Let me know if you have any suggestions for making ratios play a bigger part. I'm open to change.

**Comment by celsomiranda** [comment]
I guess it makes sense. I was too quick to jump the gun on this one.

That said, maybe there's a way to add some control to `line-height` and `margin`.

**Comment by corysimmons** [comment]
It's possible, but I can't think of a way.

I'm going to close this one but if you have any suggestions for getting `$ratio` in the mix, let me know and I'll reopen.

**Comment by celsomiranda** [comment]
Maybe you could create a variable for the line-heights that interacts with the margins and not rely on a fixed value like $golden?

**Comment by corysimmons** [comment]
I thought about it, but `$golden` works pretty perfect for almost any situation. Everything looks good with it and I'd prefer not to have _too_ many variables if I can help it.

Besides, the `// Reset` should be considered just that - a reset that you can override with your own values if you'd like.

I might abstract this out in the future if there's more demand for something like this, but right now I think it works pretty well and don't want to make the `// Settings` too scary by adding things in like `$line-height-ratio` etc.

**Comment by corysimmons** [comment]
Seriously `$golden` just looks so damn good. =)

**Comment by corysimmons** [comment]
Reopening this as it's an easy fix and adding one more setting in exchange for granular control over line-height is a good trade.

Will implement.

**Comment by celsomiranda** [comment]
Thanks. :+1:

**Comment by corysimmons** [comment]
Thank *you* for taking the time to examine the source and offering good suggestions. =)

Fixed https://github.com/corysimmons/typographic/commit/f3e9c0c9d3214a978d250cb2b3548a46b0146781
